---
- name: Configure RPI4
  hosts: all

  vars:
    # List of channels with latest versions is available at
    # <https://update.k3s.io/v1-release/channels>.
    k3s_version: v1.28.15+k3s1

  tasks:
    - name: Update all packages to latest version.
      ansible.builtin.import_tasks: tasks/update_packages.yml
    - name: Ensure local DNS resolver is running.
      ansible.builtin.import_tasks: tasks/dns_resolver.yml
    - name: Ensure k3s is running.
      ansible.builtin.import_tasks: tasks/k3s.yml
