---
#
# Install needed packages and update all packages to latest version
#

- name: Update apt cache if needed.
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
- name: Clean up no longer useful package files
  become: true
  ansible.builtin.apt:
    autoclean: true
- name: Remove unused dependency packages
  become: true
  ansible.builtin.apt:
    autoremove: true
- name: Update all packages to latest version.
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  when: packages_update
- name: Install needed packages.
  become: true
  ansible.builtin.apt:
    name: "{{ packages_needed_packages }}"
    state: present
