---
#
# Set dns_resolver_package as a local DNS resolver.
#
# Setup and configure DNS resolver in order to be used as a local DNS resolver.
#

- name: Update apt cache if needed.
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
- name: Install DNS resolver package if needed.
  become: true
  ansible.builtin.apt:
    name: "{{ dns_resolver_package }}"
    state: present
- name: Ensure DNS resolver is started and enabled.
  become: true
  ansible.builtin.service:
    name: "{{ dns_resolver_service }}"
    state: started
    enabled: true
- name: Check resolv.conf file status.
  become: true
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: dns_resolver_resolv_conf_stat
- name: Remove resolv.conf if it is a link (dynamically generated).
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  when: >
    dns_resolver_resolv_conf_stat.stat.islnk is defined
    and dns_resolver_resolv_conf_stat.stat.islnk
- name: Populate resolv.conf to use unbound.
  become: true
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
